from sqlalchemy import Column, Integer, String, DateTime, Boolean, Float
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class MaestroFamilia(Base):
    __tablename__ = 'tbMaestroFamilia'

    IDTipo = Column(Integer, primary_key=True)
    IDFamilia = Column(Integer)
    DescFamilia = Column(String)
    Dto1 = Column(Float)
    Dto2 = Column(Float)
    Dto3 = Column(Float)
    FechaCreacionAudi = Column(DateTime)
    FechaModificacionAudi = Column(DateTime)
    UsuarioAudi = Column(String)
    NumCorrelativo = Column(Integer)
    IDProveedor = Column(Integer)
    CCVenta = Column(Integer)
    CCExport = Column(Integer)
    CCCompra = Column(Integer)
    CCImport = Column(Integer)
    CCVentaRegalo = Column(Integer)
    CCGastoRegalo = Column(Integer)
    CCStocks = Column(Integer)
    CCVentaGRUPO = Column(Integer)
    CCExportGRUPO = Column(Integer)
    CCImportGRUPO = Column(Integer)
    CCCompraGRUPO = Column(Integer)
    MostrarenTPV = Column(Boolean)
    CaracteristicaArticulo1 = Column(String)
    CaracteristicaArticulo2 = Column(String)
    CaracteristicaArticulo3 = Column(String)
    CaracteristicaArticulo4 = Column(String)
    CaracteristicaArticulo5 = Column(String)
    Precinta = Column(String)
    PorcMermaMaxima = Column(Float)
    IDCodigo = Column(Integer)
    IDConfig = Column(Integer)
    DescConfig = Column(String)
    PorcRecepcionMaximo = Column(Float)
    ConsejoRegulador = Column(String)
    SeguimientoPrecinta = Column(Boolean)
    RefProductoSilicie = Column(String)
    Contenedor = Column(String)
    Embalaje = Column(String)
    ComponenteAdicional = Column(String)
    UsuarioCreacionAudi = Column(String)
